### ISSUE TITLE
[ROADMAP] 2.0 Release

### ISSUE THREAD

**Issue by piguycs** [RocKing1001/AllayInABottle#7]
**Summary**
I created this mod back when I was still pretty new to java, and had a lot of help when setting up the project for cross compatibility between forge and fabric. Right now, I am a lot more confident and I wish to make the mod easier to update, as my current code is, for a lack of a better word, shit. So I will be releasing a 1.0 version where I will be rewriting most of the code in a way which I understand, and add a lot of important features which I did not have in my previous versions.

**TODO**
- [ ] Hold item NBT for items which the allay is holding, and the allay's age
- [ ] Show up in JEI and other menus for forge and fabric (forge is broken right now)
- [ ] Fix a bug where the item just disappears if your inventory is full
- [ ] Fix my dev environment where forge builds fail in dev mode
- [x] Official quilt support

**Comments**
N/A

**Comment by piguycs** [comment]
and 1.21 support
